# Generated by Django 5.2.3 on 2025-08-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='view_all',
            field=models.BooleanField(default=False),
        ),
    ]
