# Generated by Django 5.2.3 on 2025-12-05 14:09

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_customer_view_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': [django.db.models.functions.text.Lower('customer_name')]},
        ),
    ]
