# Generated by Django 5.2.3 on 2025-08-08 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('today_recieved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_recieved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesWeb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('next_meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_done', models.BooleanField(default=False)),
                ('payment_recieved', models.IntegerField(blank=True, default=0, null=True)),
                ('final_due_date', models.DateField(blank=True, null=True)),
                ('soa_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_pdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_cdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_tt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_pdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_cdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_tt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('call_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.callstatus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
                ('hardwarematerials', models.ManyToManyField(blank=True, null=True, to='master.hardwarematerial')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.orderstatustype')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.paymentmethod')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.prospect')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timbermaterials', models.ManyToManyField(blank=True, null=True, to='master.timbermaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meetinglog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=250, null=True)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('meeting_status', models.BooleanField(default=False)),
                ('payment_collected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sales_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesweb')),
            ],
        ),
        migrations.CreateModel(
            name='SalesWebHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('next_meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_done', models.BooleanField(default=False)),
                ('payment_recieved', models.IntegerField(blank=True, default=0, null=True)),
                ('final_due_date', models.DateField(blank=True, null=True)),
                ('soa_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_pdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_cdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_tt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_pdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_cdc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_tt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.callstatus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
                ('hardwarematerials', models.ManyToManyField(blank=True, to='master.hardwarematerial')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.orderstatustype')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.paymentmethod')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.prospect')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salesweb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='sales.salesweb')),
                ('timbermaterials', models.ManyToManyField(blank=True, to='master.timbermaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
