# Generated by Django 5.2.3 on 2025-08-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleswebhistory',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='saleswebhistory',
            name='mode_of_collection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
