# Generated by Django 5.2.3 on 2025-08-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_saleswebhistory_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesweb',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='salesweb',
            name='mode_of_collection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
