# Generated by Django 5.2.3 on 2025-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_salesweb_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesweb',
            name='mode_of_collection',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleswebhistory',
            name='mode_of_collection',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
