# Generated by Django 5.2.3 on 2025-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_customer_view_all'),
        ('sales', '0004_alter_salesweb_mode_of_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesweb',
            name='order_value',
        ),
        migrations.RemoveField(
            model_name='saleswebhistory',
            name='order_value',
        ),
        migrations.AlterField(
            model_name='meetinglog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='meetinglog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesweb',
            name='hardwarematerials',
            field=models.ManyToManyField(blank=True, to='master.hardwarematerial'),
        ),
        migrations.AlterField(
            model_name='salesweb',
            name='timbermaterials',
            field=models.ManyToManyField(blank=True, to='master.timbermaterial'),
        ),
    ]
