# Generated by Django 5.2.3 on 2025-09-04 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_customer_view_all'),
        ('sales', '0005_remove_salesweb_order_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesweb',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='salesweb',
            name='collected_amount_now',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesweb',
            name='collected_amount_now_two',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesweb',
            name='hardwarecategories',
            field=models.ManyToManyField(blank=True, to='master.hardwarematerialcategory'),
        ),
        migrations.AddField(
            model_name='salesweb',
            name='timbercategories',
            field=models.ManyToManyField(blank=True, to='master.timbermaterialcategory'),
        ),
        migrations.AlterField(
            model_name='salesweb',
            name='payment_recieved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CollectionAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salesweb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived_history', to='sales.salesweb')),
            ],
        ),
    ]
