# Generated by Django 5.2.3 on 2025-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesweb_options_salesweb_collected_amount_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalessummary',
            name='timestamp',
            field=models.DateField(unique=True),
        ),
    ]
